name: Pipeline Base - GitHub Actions

on:
  push:
    branches: [ "main", "develop" ]

  pull_request:
    branches: [ "main", "develop" ]

  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_NAME: esteira-devsecops-open-source

jobs:
  checkout-node:
    name: Checkout e configuração do Node.js
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Validar versão do Node.js e NPM
        run: |
          node --version
          npm --version

      - name: Listar arquivos do projeto
        run: ls -la

      - name: Instalar dependências
        run: npm install

      - name: Executar lint
        run: npm run lint
        
  gitleaks:
    name: Scan de Segredos (Gitleaks)
    runs-on: ubuntu-latest
    needs: checkout-node
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Executar Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Salvar Relatório Gitleaks
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: results.json

  semgrep:
    name: SAST (Semgrep)
    runs-on: ubuntu-latest
    needs: checkout-node
    container:
      image: semgrep/semgrep
    steps:
      - name: Baixar código
        uses: actions/checkout@v4
      - name: Executar Semgrep
        run: semgrep ci --severity ERROR --json --output=semgrep.json
      - name: Salvar Relatório Semgrep
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.json

  docker-build:
    name: Build da imagem Docker
    runs-on: ubuntu-latest
    needs: [checkout-node, gitleaks, semgrep]

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Validar existência do Dockerfile
        run: |
          test -f Dockerfile
          echo "Dockerfile encontrado com sucesso."

      - name: Padronizar nome da imagem Docker
        run: |
          echo "Nome da imagem: $IMAGE_NAME"
          echo "Tag do commit: ${{ github.sha }}"

      - name: Construir imagem Docker
        run: |
          docker build \
            --file Dockerfile \
            --tag $IMAGE_NAME:${{ github.sha }} \
            --tag $IMAGE_NAME:latest \
            .

      - name: Validar imagem Docker gerada
        run: |
          docker images | grep $IMAGE_NAME
          echo "Imagem Docker gerada com sucesso."